const menuButton = document.querySelector('.menu-button');
const nav = document.querySelector('.nav-links');
if (menuButton && nav) menuButton.addEventListener('click', () => { const open = nav.classList.toggle('open'); menuButton.setAttribute('aria-expanded', String(open)); });

document.querySelectorAll('.password-toggle').forEach((button) => button.addEventListener('click', () => { const input = button.closest('.password-field').querySelector('input'); const visible = input.type === 'text'; input.type = visible ? 'password' : 'text'; button.textContent = visible ? 'Show' : 'Hide'; }));
function setMessage(form, text, isError = false) { const message = form.querySelector('.form-message'); message.textContent = text; message.classList.toggle('error', isError); }
async function sendAuthRequest(url, payload) { const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Please try again.'); return data; }

const loginForm = document.querySelector('#login-form');
if (loginForm) loginForm.addEventListener('submit', async (event) => { event.preventDefault(); if (!loginForm.checkValidity()) return setMessage(loginForm, 'Please enter a valid email and password.', true); const [email, password] = loginForm.querySelectorAll('input:not([type=checkbox])'); const button = loginForm.querySelector('button[type=submit]'); button.disabled = true; button.textContent = 'Signing in…'; setMessage(loginForm, ''); try { await sendAuthRequest('/api/login', { email: email.value, password: password.value }); window.location.href = 'dashboard.html'; } catch (error) { setMessage(loginForm, error.message, true); button.disabled = false; button.innerHTML = 'Sign in <b>→</b>'; } });

const registerForm = document.querySelector('#register-form');
if (registerForm) registerForm.addEventListener('submit', async (event) => { event.preventDefault(); if (!registerForm.checkValidity()) return setMessage(registerForm, 'Please complete all fields and accept the terms.', true); const [firstName, lastName, email, password] = registerForm.querySelectorAll('input:not([type=checkbox])'); const button = registerForm.querySelector('button[type=submit]'); button.disabled = true; button.textContent = 'Creating account…'; setMessage(registerForm, ''); try { await sendAuthRequest('/api/register', { firstName: firstName.value, lastName: lastName.value, email: email.value, password: password.value }); window.location.href = 'dashboard.html'; } catch (error) { setMessage(registerForm, error.message, true); button.disabled = false; button.innerHTML = 'Create my account <b>→</b>'; } });

const calculator = document.querySelector('#calculator-form');
if (calculator) calculator.addEventListener('submit', (event) => { event.preventDefault(); const day = Number(document.querySelector('#calc-day').value), month = Number(document.querySelector('#calc-month').value), year = Number(document.querySelector('#calc-year').value), result = calculator.querySelector('.calc-result'); if (!Number.isInteger(day) || !Number.isInteger(month) || !Number.isInteger(year) || day < 1 || day > 31 || month < 1 || month > 12 || year < 1900 || year > new Date().getFullYear()) { result.textContent = 'Please enter a valid day, month and year.'; return; } let total = `${String(day).padStart(2, '0')}${String(month).padStart(2, '0')}${year}`.split('').reduce((sum, digit) => sum + Number(digit), 0); while (total > 9 && total !== 11 && total !== 22) total = String(total).split('').reduce((sum, digit) => sum + Number(digit), 0); result.innerHTML = `<span>Your life path number</span><strong>${total}</strong><p>Use this as a starting point for self-reflection.</p>`; });

const registerPassword = document.querySelector('#register-password');
if (registerPassword) registerPassword.addEventListener('input', () => { const strength = registerPassword.value.length >= 10 ? 4 : registerPassword.value.length >= 8 ? 3 : registerPassword.value.length >= 6 ? 2 : registerPassword.value.length ? 1 : 0; document.querySelectorAll('.password-strength span').forEach((bar, index) => bar.classList.toggle('filled', index < strength)); });

const dashboard = document.querySelector('#dashboard');
if (dashboard) { fetch('/api/me', { credentials: 'same-origin' }).then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then(({ user }) => { dashboard.querySelector('[data-user-name]').textContent = `${user.firstName} ${user.lastName}`; dashboard.querySelector('[data-user-email]').textContent = user.email; dashboard.hidden = false; }).catch(() => { window.location.href = 'login.html'; }); document.querySelector('#logout-button').addEventListener('click', async () => { await fetch('/api/logout', { method: 'POST', credentials: 'same-origin' }); window.location.href = 'index.html'; }); }
